# Copyright (c) 2018-2019 AccelByte Inc. All Rights Reserved.
# This is licensed software from AccelByte Inc, for limitations
# and restrictions contact your company contract manager.

version: '3'
services:
  envoy:
    image: envoyproxy/envoy:v1.22.5
    command: ["--service-cluster", "envoyproxy", "--config-path", "/etc/envoy/envoy.yaml"]
    ports:
      - "10000:10000"
    volumes:
      - ./compose-config/envoy.yaml:/etc/envoy/envoy.yaml
    extra_hosts:
      - host.docker.internal:host-gateway

  grafana-agent:
    image: grafana/agent:main
    command: ["-config.expand-env", "-config.file", "/etc/agent/agent.yaml"]
    environment:
      - GRAPHANA_CLOUD_TRACES_ENDPOINT
      - GRAPHANA_CLOUD_TRACES_BASIC_USERNAME
      - GRAPHANA_CLOUD_TRACES_BASIC_PASSWORD
      - GRAPHANA_CLOUD_TRACES_SAMPLING_PERCENTAGE
      - GRAPHANA_CLOUD_METRICS_ENDPOINT
      - GRAPHANA_CLOUD_METRICS_BASIC_USERNAME
      - GRAPHANA_CLOUD_METRICS_BASIC_PASSWORD
    volumes:
      - "./compose-config/graphana-agent.yaml:/etc/agent/agent.yaml"
    ports:
      - "9411:9411"   # Zipkin receiver
    extra_hosts:
      - host.docker.internal:host-gateway

  fluentd-loki:
    image: grafana/fluent-plugin-loki:master  # based on 1.9 and not having the updated http plugin for json-array
    command: ["-v"]
    environment:
      - LOKI_URL
      - LOKI_USERNAME
      - LOKI_PASSWORD
    volumes:
      - ./compose-config/fluent-loki.conf:/fluentd/etc/fluent.conf
    ports:
      - "24225:24225"
      - "24225:24225/udp"

