# Copyright (c) 2018-2019 AccelByte Inc. All Rights Reserved.
# This is licensed software from AccelByte Inc, for limitations
# and restrictions contact your company contract manager.

version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6565:6565"
      - "8080:8080"
    environment:
      - AB_BASE_URL
      - AB_CLIENT_ID
      - AB_CLIENT_SECRET
      - AB_NAMESPACE
      - PLUGIN_GRPC_SERVER_AUTH_ENABLED
      - OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://host.docker.internal:9411/api/v2/spans
      - OTEL_TRACES_EXPORTER=zipkin
      - OTEL_METRICS_EXPORTER=none
      - OTEL_SERVICE_NAME=CustomMatchmakingFunctionServerJava
      - OTEL_PROPAGATORS=b3multi
    logging:
      driver: fluentd
      options:
        fluentd-address: "host.docker.internal:24225"
        fluentd-async-connect: "true"
        tag: docker
    extra_hosts:
      - host.docker.internal:host-gateway


