receivers:
  zipkin:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'CustomMatchMakingFunctionGRPCJava-metrics'
          metrics_path: '/actuator/prometheus'
          scrape_interval: 60s
          scrape_timeout: 10s
          static_configs:
            - targets: ['host.docker.internal:8080']

exporters:
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true
  otlp/honeycomb:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": "${HONEYCOMB_API_KEY}"
  otlp/graphana-cloud:
    endpoint: "tempo-us-central1.grafana.net:443"
    headers:
      authorization: Basic ${GRAPHANA_CLOUD_TRACES_BASIC_AUTH}
      # username: 272095
  otlp/graphana-local:
    endpoint: tempo:4317
    tls:
      insecure: true
#  prometheus:
#    endpoint: "0.0.0.0:8889"
#    const_labels:
#      label1: value1
  prometheusremotewrite:
    endpoint: 'http://prometheus:9090/api/v1/write'
    tls:
     insecure: true

#  otlp/honeycomb-metrics:
#    endpoint: "api.honeycomb.io:443"
#    headers:
#      "x-honeycomb-team": "${HONEYCOMB_API_KEY}"
#      "x-honeycomb-dataset": custommatchmakingfunctionjava

processors:
  batch:
  tail_sampling:
    policies:
      - type: string_attribute
        string_attribute:
          key: http.target
          values:
            - ^\/(?:metrics\/.*|health.*|actuator\/.*)$
          enabled_regex_matching: true
          invert_match: true
      - type: status_code
        status_code:
          status_codes:
            - ERROR
      - type: latency
        latency:
          threshold_ms: 5000
      - type: probabilistic
        probabilistic:
          sampling_percentage: ${GRAPHANA_CLOUD_TRACES_SAMPLING_PERCENTAGE}

service:
  telemetry:
    logs:
      level: "info"
  pipelines:
    traces:
      receivers: [zipkin]
      processors: [batch,tail_sampling]
      exporters: [otlp/graphana-local,otlp/honeycomb,otlp/graphana-cloud,jaeger]
    metrics:
      receivers: [prometheus]
      processors: [batch]
      exporters: [prometheusremotewrite]
